Leaderboard: API
misikirdelelew/Leadboard pull request #2
Opened 2023-03-09 20:56 UTC by misikirdelelew

In This PR I have done the following

- I created a new game with the name using the API.
The "Refresh" button will get all scores for a game created by me from the API using  JSON format
The form "Submit" button will save a score for a game created by me
Used arrow functions 
Used async and await JavaScript features to consume the API.

2023-03-09 21:15 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @misikirdelelew, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 21:15 UTC, anagudelogu commented on README.md
> +
- [ ] You did a great job documenting your project! 🚀 However, please consider adding a link to the LICENSE file, so others can easily refer to it! 🤓 🔧 

- [ ] Also please consider removing the NOTE at the end, it is supposed to be a guideline for you when you choose a LICENSE! 🤓 🔧

2023-03-09 21:15 UTC, anagudelogu commented on src/modules/game.js
> +// const gameID = '4oNvU3Bhjf2ub7nbIBB5';
- [ ] Please don't forget to remove old pieces of commented code, they make your code base look ugly and make it less readable. 🤓 🔧

2023-03-09 21:15 UTC, anagudelogu commented on src/modules/game.js
> +};
- [ ] Since you're using ES6 syntax, please consider using import/exports instead of commonJS's `module.exports`! 🤓 🔧 

```suggestion
export {
  addScore,
  showScores,
};
```

2023-03-09 21:15 UTC, anagudelogu commented on src/modules/toast.js
> +module.exports = showToast;
I loved this feature, kudos for this! 🚀 

- [ ] **[OPTIONAL]** The same happens here, since you're using ES6 syntax, please consider using import/exports instead of commonJS's `module.exports`, I'm marking this as optional since this feature isn't part of the requirements, however, please be consistent with the ES6 syntax! 🤓 🔧 


```suggestion
export const showToast = (message) => {
  const toast = document.getElementById('toast');
  toast.innerText = message;
  toast.style.display = 'block';
  setTimeout(() => {
    toast.style.display = '';
  }, 3000);
};


```

2023-03-10 06:30 UTC, wayungi approved these changes
Hi @misikirdelelew , 
![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work implementing the requested changes, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] Profesional README ✔️ 
- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔
- [ ] No merge conflicts ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 06:41 UTC, merged